"""add_rate_to_project_plants

Revision ID: 8d5f907b2aa3
Revises: b44c275c7285
Create Date: 2026-08-12 13:14:05.725760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d5f907b2aa3'
down_revision: Union[str, None] = 'b44c275c7285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectplants', sa.Column('rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projectplants', 'rate')
    # ### end Alembic commands ###
