"""add_boq_fields_to_project_plants

Revision ID: b44c275c7285
Revises: b3f1c9d2e5a7
Create Date: 2026-08-11 18:59:51.902852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b44c275c7285'
down_revision: Union[str, None] = 'b3f1c9d2e5a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.drop_constraint('project_share_links_token_key', 'project_share_links', type_='unique')
    op.add_column('projectplants', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('projectplants', sa.Column('unit', sa.String(), nullable=True))
    op.add_column('projectplants', sa.Column('optimum_height_size', sa.String(), nullable=True))
    op.drop_constraint('taxons_parent_id_fkey', 'taxons', type_='foreignkey')
    op.create_foreign_key(None, 'taxons', 'taxons', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taxons', type_='foreignkey')
    op.create_foreign_key('taxons_parent_id_fkey', 'taxons', 'taxons', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('projectplants', 'optimum_height_size')
    op.drop_column('projectplants', 'unit')
    op.drop_column('projectplants', 'quantity')
    op.create_unique_constraint('project_share_links_token_key', 'project_share_links', ['token'])
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.alter_column('categories', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('categories', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
