/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AuthenticatedTaxonomyRouteImport } from './routes/_authenticated/taxonomy'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedPlantsIndexRouteImport } from './routes/_authenticated/plants/index'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects/$id'
import { Route as AuthenticatedPlantsImportRouteImport } from './routes/_authenticated/plants/import'
import { Route as AuthenticatedPlantsIdRouteImport } from './routes/_authenticated/plants/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTaxonomyRoute = AuthenticatedTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlantsIndexRoute =
  AuthenticatedPlantsIndexRouteImport.update({
    id: '/plants/',
    path: '/plants/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlantsImportRoute =
  AuthenticatedPlantsImportRouteImport.update({
    id: '/plants/import',
    path: '/plants/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlantsIdRoute = AuthenticatedPlantsIdRouteImport.update({
  id: '/plants/$id',
  path: '/plants/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/taxonomy': typeof AuthenticatedTaxonomyRoute
  '/share/$token': typeof ShareTokenRoute
  '/plants/$id': typeof AuthenticatedPlantsIdRoute
  '/plants/import': typeof AuthenticatedPlantsImportRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/plants/': typeof AuthenticatedPlantsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/taxonomy': typeof AuthenticatedTaxonomyRoute
  '/share/$token': typeof ShareTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/plants/$id': typeof AuthenticatedPlantsIdRoute
  '/plants/import': typeof AuthenticatedPlantsImportRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/plants': typeof AuthenticatedPlantsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/taxonomy': typeof AuthenticatedTaxonomyRoute
  '/share/$token': typeof ShareTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/plants/$id': typeof AuthenticatedPlantsIdRoute
  '/_authenticated/plants/import': typeof AuthenticatedPlantsImportRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/plants/': typeof AuthenticatedPlantsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categories'
    | '/taxonomy'
    | '/share/$token'
    | '/plants/$id'
    | '/plants/import'
    | '/projects/$id'
    | '/plants/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/categories'
    | '/taxonomy'
    | '/share/$token'
    | '/'
    | '/plants/$id'
    | '/plants/import'
    | '/projects/$id'
    | '/plants'
    | '/projects'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/categories'
    | '/_authenticated/taxonomy'
    | '/share/$token'
    | '/_authenticated/'
    | '/_authenticated/plants/$id'
    | '/_authenticated/plants/import'
    | '/_authenticated/projects/$id'
    | '/_authenticated/plants/'
    | '/_authenticated/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/taxonomy': {
      id: '/_authenticated/taxonomy'
      path: '/taxonomy'
      fullPath: '/taxonomy'
      preLoaderRoute: typeof AuthenticatedTaxonomyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plants/': {
      id: '/_authenticated/plants/'
      path: '/plants'
      fullPath: '/plants/'
      preLoaderRoute: typeof AuthenticatedPlantsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plants/import': {
      id: '/_authenticated/plants/import'
      path: '/plants/import'
      fullPath: '/plants/import'
      preLoaderRoute: typeof AuthenticatedPlantsImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plants/$id': {
      id: '/_authenticated/plants/$id'
      path: '/plants/$id'
      fullPath: '/plants/$id'
      preLoaderRoute: typeof AuthenticatedPlantsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedTaxonomyRoute: typeof AuthenticatedTaxonomyRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPlantsIdRoute: typeof AuthenticatedPlantsIdRoute
  AuthenticatedPlantsImportRoute: typeof AuthenticatedPlantsImportRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedPlantsIndexRoute: typeof AuthenticatedPlantsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedTaxonomyRoute: AuthenticatedTaxonomyRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPlantsIdRoute: AuthenticatedPlantsIdRoute,
  AuthenticatedPlantsImportRoute: AuthenticatedPlantsImportRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedPlantsIndexRoute: AuthenticatedPlantsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
